uploads = []
outputs = []

[[generated]]
id = "vI1o5_OizYR0kGuYKvOjQ"
uri = "file://artifacts/mockup-sandbox/public/images/academy-hero.png"
type = "image"
title = "generated_image"

[[generated]]
id = "0hQtMj_BjNsgWR7pPbKUT"
uri = "file://artifacts/mockup-sandbox/public/images/academy-meditation.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Ptx0uA2MkVdaPdKp6JZf0"
uri = "file://artifacts/mockup-sandbox/public/images/academy-lotus.png"
type = "image"
title = "generated_image"

[[generated]]
id = "jra7x4eI4AmCyerMO_uqk"
uri = "file://artifacts/mockup-sandbox/public/images/pillar-swastha.png"
type = "image"
title = "generated_image"

[[generated]]
id = "s9SaJjwsOE6Jz-YeBpfke"
uri = "file://artifacts/mockup-sandbox/public/images/pillar-sikshya.png"
type = "image"
title = "generated_image"

[[generated]]
id = "bRNOA3h_ucSNSkAcSDHod"
uri = "file://artifacts/mockup-sandbox/public/images/pillar-sanskar.png"
type = "image"
title = "generated_image"

[[generated]]
id = "cY3NOSWDh5fRhAyDP24_3"
uri = "file://artifacts/mockup-sandbox/public/images/pillar-sadvritta.png"
type = "image"
title = "generated_image"

[[generated]]
id = "yWz_FCjFEtl1IZAfEKNDk"
uri = "file://artifacts/mockup-sandbox/public/images/pillar-samriddhi.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Uace1N9jg1tObG6rDVeeO"
uri = "file://artifacts/mockup-sandbox/public/images/pillar-shanti.png"
type = "image"
title = "generated_image"

[[generated]]
id = "qsF_sDuep8LAl6vH6mWB9"
uri = "file://artifacts/mockup-sandbox/public/images/discover-guru.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Rwq2UQYcypTrsgvvHdm19"
uri = "file://artifacts/mockup-sandbox/public/images/discover-ashram.png"
type = "image"
title = "generated_image"

[[generated]]
id = "elAGzfgmvKb2t5Cz7Mh03"
uri = "file://artifacts/about-academy/public/images/meditation-hero.png"
type = "image"
title = "generated_image"

[[generated]]
id = "_YZw2ZZuKmzneVv9LZa5n"
uri = "file://artifacts/about-academy/public/images/meditation-kundalini.png"
type = "image"
title = "generated_image"

[[generated]]
id = "KURdpiEHkZkgp5pEHMn62"
uri = "file://artifacts/about-academy/public/images/meditation-origins.png"
type = "image"
title = "generated_image"

[[generated]]
id = "bXhDroeXd4xFUroWDLafS"
uri = "file://artifacts/about-academy/public/images/meditation-benefits.png"
type = "image"
title = "generated_image"

[[generated]]
id = "6urrcDNEBQMwpV8fzgSU_"
uri = "file://artifacts/about-academy/public/images/meditation-howitworks.png"
type = "image"
title = "ashram meditation how it works"
