// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/academy-variants/ForestHermitage.tsx": () => import("../components/mockups/academy-variants/ForestHermitage.tsx"),
  "./components/mockups/academy-variants/SacredNight.tsx": () => import("../components/mockups/academy-variants/SacredNight.tsx"),
  "./components/mockups/academy-variants/TempleAtDawn.tsx": () => import("../components/mockups/academy-variants/TempleAtDawn.tsx"),
  "./components/mockups/chakra-nadi/Variant_A.tsx": () => import("../components/mockups/chakra-nadi/Variant_A.tsx"),
  "./components/mockups/chakra-nadi/Variant_B.tsx": () => import("../components/mockups/chakra-nadi/Variant_B.tsx"),
  "./components/mockups/chakra-nadi-preserved/ChakraNadi.tsx": () => import("../components/mockups/chakra-nadi-preserved/ChakraNadi.tsx"),
  "./components/mockups/hero-variants/Banner.tsx": () => import("../components/mockups/hero-variants/Banner.tsx"),
  "./components/mockups/hero-variants/Compact.tsx": () => import("../components/mockups/hero-variants/Compact.tsx"),
  "./components/mockups/kundalini-rising/KundaliniRising.tsx": () => import("../components/mockups/kundalini-rising/KundaliniRising.tsx"),
  "./components/mockups/initiative-cards/OptionA.tsx": () => import("../components/mockups/initiative-cards/OptionA.tsx"),
  "./components/mockups/initiative-cards/OptionB.tsx": () => import("../components/mockups/initiative-cards/OptionB.tsx"),
  "./components/mockups/initiative-cards/OptionC.tsx": () => import("../components/mockups/initiative-cards/OptionC.tsx")
};
